stages:
  - build
  - upload

variables:
  GO_VERSION: "1.20.14"
  PACKAGE_REGISTRY_PROJECT_ID: $CI_PROJECT_ID

before_script:
  - apt-get update && apt-get install -y make
  - export VERSION=$(cat version.txt)
  - export TIMESTAMP=$(date +%Y%m%d%H%M%S%3N)
  - export SHORT_HASH=$(git rev-parse --short HEAD)
  - export PACKAGE_VERSION="${VERSION}-${TIMESTAMP}-${SHORT_HASH}"
  - export PACKAGE_REGISTRY_URL="$CI_API_V4_URL/projects/$PACKAGE_REGISTRY_PROJECT_ID/packages/generic/fluentbit-rabbitmq-plugin/$PACKAGE_VERSION"

build:
  stage: build
  image: golang:${GO_VERSION}-bullseye
  script:
    - go install github.com/fluent/fluent-bit-go/output@latest
    - go install github.com/rabbitmq/amqp091-go@latest
    - mkdir -p /go/src
    - cp ./*.go /go/src/
    - cp ./go.mod /go/src/
    - cp ./go.sum /go/src/
    - cp ./Makefile /go/src/
    - cd /go/src
    - make
  artifacts:
    paths:
      - /go/src/out_rabbitmq.so

upload:
  stage: upload
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file /go/src/out_rabbitmq.so "$PACKAGE_REGISTRY_URL/out_rabbitmq.so"'
